#!/bin/bash

echo -n "file name "
read STR

exec ffmpeg -f alsa -ac 2 -i pulse -f x11grab -r 60 -s 1366x768 -i :0.0 \
-vcodec libx264 -pix_fmt yuv420p -preset ultrafast -crf 0 -threads 0 \
-acodec pcm_s16le -y $STR.mkv

